### ISSUE TITLE
One page template glossary

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/components#50]
As a non-technical contributor 
I want to view a single page of all available templates
So I can easily select what I want to use to build my page

**Comment by sjmog** [comment]
IMO this should be split with:
- one side name/description/possible locals (in a table), and 
- the other side tabs: rendered output/ERB/HAML.

Kinda like Stripe. Diagram:

```
-------------------------------------------
| <template name >   |  Live / ERB / HAML  |
|                    |                     |
| <description>      |                     |
|                    |                     |
| <table of locals>  |                     |
-------------------------------------------
```

**Comment by sjmog** [comment]
So a two-up block is suitable for this

**Comment by sjmog** [comment]
Also @pitchinvasion how does this relate to #19

**Comment by pitchinvasion** [comment]
I agree with the proposal.

The other ticket is an example of one that's a bit too vague for managing our time - this is an issue to specifically to create a single page with all the templates on it. If we need to add docs for other pages we should create a specific issue for that as well. Just that at the moment otherwise we'll all get a bit lost about who does what!

**Comment by sjmog** [comment]
Good call :)

**Comment by sjmog** [comment]
Fixed in `website_docs` repo.
