### ISSUE TITLE
Build layout for component glossary

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/components#60]

**Comment by pitchinvasion** [comment]
CSS/HTML design for component glossary

**Comment by roidriscoll** [comment]
![docslayout](https://cloud.githubusercontent.com/assets/2243253/7815071/1acd485e-03be-11e5-878e-7a0d7ae296ef.jpg)
![docslayout2](https://cloud.githubusercontent.com/assets/2243253/7815076/2013b5e6-03be-11e5-83df-ef28f3419a6a.jpg)

**Comment by sjmog** [comment]
Love it @roi - if I had suggestions, they would be:

- Info on the left could remove the 'comprised of' and 'related elements' section and instead give a list of the locals the block expects, along with a brief description of each one (i.e. in a table, like Stripe)
- Top 'Layout/HAML/Sass' -> could we make these more 'tab-like'? At the moment I worry they look a bit like 'vertical' buttons

This is the sex, though. We have a blockquote element but it doesn't look anything as sexy as yours

**Comment by roidriscoll** [comment]
Thanks @sjmog, I shall be implementing your suggestions fo' sho. :space_invader:

**Comment by sjmog** [comment]
I'm researching how to pull in files automatically so this always stays up-to-date when new components are added (automating documentation)

**Comment by sjmog** [comment]
Fixed in `website_docs` repo.
